refactor: normalize input amounts
ArkEcosystem/platform-sdk pull request #1621
Opened 2021-05-28 07:20 UTC by axeldelamarre

## Summary

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2021-05-28 12:25 UTC, faustbrian commented
@axeldelamarre conflicts

2021-05-31 15:25 UTC, axeldelamarre commented
egld: already normalized, not sure about fee
nano: already in normalized
neo: using neo 2 lib, neo 3 available

2021-06-01 01:00 UTC, faustbrian requested changes
Looks good except for changing some constructors from using an object to multiple arguments. The object makes it easier to see what argument is what without having to go check the constructor or rely on an IDE.

2021-06-01 06:17 UTC, axeldelamarre commented
> Looks good except for changing some constructors from using an object to multiple arguments. The object makes it easier to see what argument is what without having to go check the constructor or rely on an IDE.

The constructor is private, so always visible and close to __construct, and only has 2 arguments. The object pattern is useful when there is lots of optional arguments, but in this case, it introduces any's which is a big no no in my book, IDE or no.

2021-06-01 07:01 UTC, faustbrian commented on packages/platform-sdk-eth/src/services/transaction.ts
> +		this.#web3 = new Web3(this.#peer);
This is not a Web3 compatible host, that's why there's still the TODO.

2021-06-01 07:13 UTC, merged